### ISSUE TITLE
[1.14.4] Doesn't appear to spawn

### ISSUE THREAD

**Issue by noobanidus** [RedstoneTim/aswampscurse#1]
This doesn't appear to spawn on our server. I've looked through the code and, while the entity placement is registered, I don't see any instances of it being added to the swamp/swamp-tagged biome lists.

**Comment by RedstoneTim** [comment]
Thanks for opening this issue! I'm sorry that this took so long since it's really overdue and not that hard of a fix. A new version including the fix will be uploaded on curse soon.
